main_folder_path: "/Users/vitodibari/Projects/GDGProjects/photobooth/out"
cam_name: 'USB PTP Class Camera'
printer_name: 'Dai_Nippon_Printing_DP_QW410'
event_name: 'codemotion-rome-2026'
backend: "http://localhost:8000" 
